name: CI
on:
  push:
    branches: ["main"]

jobs:
  buid_apk:
    name: "Flutter build (APK)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
      - run: |
          flutter clean
          flutter pub get
          flutter --version
          flutter build apk
      - name: Retrieve Release Version
        id: versionstep
        run: |
          VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
          echo "::set-output name=VERSION::$VERSION"
      - name: Upload the APK onto Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.versionstep.outputs.VERSION }}

  buid_ios:
    name: "Flutter build (iOS)"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
      - run: |
          flutter clean
          flutter pub get
          flutter --version
          flutter build ios --no-codesign
      - name: Retrieve Release Version
        id: versionstep
        run: |
          VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
          echo "::set-output name=VERSION::$VERSION"
      - name: Upload the IPA onto Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/ipa/*.ipa"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.versionstep.outputs.VERSION }}
