name: CI
on:
  push:
    branches: ["main"]

jobs:
  buid_apk:
    name: "Flutter build (APK)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action/config@v3
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - run: flutter clean
      - run: flutter pub get
      - run: flutter --version
      - run: flutter build apk

  buid_ios:
    name: "Flutter build (iOS)"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action/config@v3
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - run: flutter clean
      - run: flutter pub get
      - run: flutter --version
      - run: flutter build ios --no-codesign
